### PR TITLE
Change shebang from python to python3: Optional

### PR DESCRIPTION
**Pull request by srevinsaju**

### CODE REVIEW

**Comment by quozl** [comment]
Depends on https://github.com/sugarlabs/typing-turtle-activity/pull/11 so taking no action yet.

**Comment by chimosky** [comment]
@srevinsaju you should add this as a commit in #11 and close it.

**Comment by Aniket21mathur** [comment]
Agreed with @chimosky.

**Comment by srevinsaju** [comment]
Merged #12 in #11

**Pull request closed without merging**
